name: Compile reports

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: apt
      run: sudo apt install -y texlive-latex-extra texlive-science latexmk curl

    - name: report1
      run: |
        cd doc/report1
        latexmk --shell-escape report_delivery1.tex -pdf

    - name: report2
      run: |
        cd doc/report2
        latexmk --shell-escape report_delivery2.tex -pdf
