name: Compile reports

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: apt
      run: sudo apt install -y texlive-latex-extra texlive-science latexmk curl

    - name: report1
      run: |
        make report_delivery1.pdf

    - name: report2
      run: |
        make report_delivery2.pdf

    - name: testzip
      run: make testzip
